import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import WagmiProviderWrapper from "@/providers/WagmiProvider";
import { cookieToInitialState } from "wagmi";
import { config } from "@/config/wagmi-config";
import { headers } from "next/headers";
import RecoidContextProvider from "@/providers/recoilContextProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));

  return (
    <html lang="en">
      <body className={inter.className}>
        <RecoidContextProvider>
          <WagmiProviderWrapper initialState={initialState}>
            {children}
          </WagmiProviderWrapper>
        </RecoidContextProvider>
      </body>
    </html>
  );
}
